### ISSUE TITLE
Googlesignin problem

### ISSUE THREAD

**Issue by nikhilreddy123456** [myflashlab/GoogleSignIn-ANE#10]
Hi sir,
        I am using gameservices ane for signin process . starting of the game it is getting signin perfectly but if i touch the screen it is getting onSigninFailure : 8 and if internet available then only i called the init() but in middle of the game if it get signin it is not showing the connecting to.. & google play games popup and if there is weak network maximum showing onSigninFailure : 8. After getting onSigninFailure : 8 it is not getting signin once again. Maximum for first signin it is showing onSigninFailure : 8 and if i touch the screen also it is showing onSigninFailure : 8. please help me how to solve this issue.

onSigninFailure : 8 ----An internal error occurred. Retrying should resolve the problem.
Note: I am not using silent login using only signin.
```actionscript
init()
function init()
{

	var options:GSignInOptions = new GSignInOptions();
	options.gamesSignIn = true; 
	options.requestScopes = ["https://www.googleapis.com/auth/games", GScopes.DRIVE_APPFOLDER];
	GSignIn.init(options);
	GSignIn.listener.addEventListener(GSignInEvents.SIGNIN_SUCCESS, onSigninSuccess);
	GSignIn.listener.addEventListener(GSignInEvents.SIGNIN_FAILURE, onSigninFailure);
    // check if user is already loggedin or not
	var account:GAccount = GSignIn.signedInAccount;
	if(account)
	{
		initGames();
	}
	signin();
	
	
}	

function onSigninSuccess(e:GSignInEvents):void
{
	notify("onSigninSuccess");
	initGames();
	
}

 function onSigninFailure(e:GSignInEvents):void
{
	notify("onSigninFailure: " + e.msg);
}
function initGames():void
{
		Games.init();

		Games.listener.addEventListener(GamesEvents.CONNECT_SUCCESS, onConnectSuccess);
		Games.listener.addEventListener(GamesEvents.CONNECT_FAILURE, onConnectFailure);
		Games.listener.addEventListener(GamesEvents.ACTIVITY_RESULT_CODES, 
 onActivityResultCodes);
	
	
	function onConnectFailure(e:GamesEvents):void
	{
		notify("onConnectFailure: " + e.msg);
	}
	
	function onActivityResultCodes(e:GamesEvents):void
	{
		// https://developers.google.com/android/reference/com/google/android/gms/games/GamesActivityResultCodes
		notify("onActivityResultCodes: " + e.status);
	}
}
    
function signin():void
		{
			if(GSignIn.signedInAccount)
			{
				notify("You are already signed in!");
			}
			else 
			{
				GSignIn.signin();
			}
		}
```

**Comment by nikhilreddy123456** [comment]
sir, please send the reply for google signin

**Comment by myflashlab** [comment]
Please check [this out](https://stackoverflow.com/questions/35229264/android-google-sign-in-fails-with-error-code-8-no-message) can you relate your question to this thread?

Also try not to request id, email or profile as mentioned [here](https://github.com/myflashlab/GameServices-ANE/wiki/B.-initializing-and-sign-in#authentication) and see how it goes.

**Comment by nikhilreddy123456** [comment]
Thank you sir it's working

**Comment by nikhilreddy123456** [comment]
Sir,
     The Cloud Save process is going fine but i found an issue that i am playing the game inbetween i am deleting the mail-id and i am entering into the game it is showing,
**onConnectFailure :17 Game Api is not Available in this game**
Please send me a solution to fix it.
