### ISSUE TITLE
Cannot Sign into My Google Acount

### ISSUE THREAD

**Issue by garymich** [myflashlab/GoogleSignIn-ANE#11]
## Environment ##
* Android API Version: AIR 30.0.0.107 for Android
* iOS Version: N/A
* AIR SDK Version: 30

## Problem Description ##
I start the application on my android phone. The console appears at the top with the message Happy bug fixing. I then click the signin button, the choose account for GoogleSignInTest popup appears and I select my account. The console shows OnSilentSignInFailure: 4: 4: followed by OnSignInFalure: 10. Then 2 more lines on the console show: idToken must be available for this method to work.

I am curious about the OnSilentSignInFailure message as I do not specify the password for my google account anywhere in the source code. I had presumed I would be prompted for my password by the application. Is that correct?

* Copy your manifest ```.xml``` file.
see attached zip at bottom

* Copy your Actionscript code.
see attached zip at bottom

## Steps to Reproduce ##
Already described in problem description. I do not know if this is related but earlier on I had an issue that the sample code would not compile because a variable which I believe was supposed to hold the value of the idToken was referenced in a function. In order to get around the issue I declared the variable but as type text as I was unsure of what dat type it is supposed to be. That allowed the compile to succeed.

[GoogleSignInTest-app.zip](https://github.com/myflashlab/GoogleSignIn-ANE/files/2246006/GoogleSignInTest-app.zip)

**Comment by myflashlab** [comment]
> idToken... I was unsure of what dat type it is supposed to be.

Correct, its data type is *String*


> I am curious about the OnSilentSignInFailure message as I do not specify the password for my google account anywhere in the source code.

you certainly shouldn't. Silent sign it works when user had previously signed in to the app and she's re-openning the app. If ```GSignIn.silentSignIn();``` fails, you must try the actual ```GSignIn.signin()``` method.

You may also check this out for more related information: https://stackoverflow.com/questions/50995021/google-play-sign-in-keeps-failing-exception-4/

*NOTE:* on such error message coming directly from the Native API, your best chance to find an answer is to search stackoverflow and ask the native devs. The ANE job is to make the Native side available to the AIR side. Questions about ANE implementations can be answered by us but what happens on server-side and non-ane related stuff can be found on stackoverflow or other forums.
