### ISSUE TITLE
Save process

### ISSUE THREAD

**Issue by BenQ12345** [myflashlab/GoogleSignIn-ANE#12]
Sir,
The Cloud Save process is going fine but i found an issue that i am playing the game inbetween i am deleting the mail-id and i am entering into the game it is showing,
onConnectFailure :17 Game Api is not Available in this game
Please send me a solution to fix it.

Waiting for your reply...

**Comment by nikhilreddy123456** [comment]
waiting for your reply.....

**Comment by myflashlab** [comment]
> inbetween i am deleting the mail-id and i am entering into the game it is showing

Can you explain this more?

**Comment by nikhilreddy123456** [comment]
Hi,

I'm using cloud save feature in the game. I have entered the game having a mail id signed in and it works like a charm. i'm closing the app now. After that i'm deleting that mail id from accounts in my mobile device. Now when i try to open the app, it says 
message:
'you are already signed in'
OnConnectFailure:17 API.games APi is not available on this device.

**Comment by nikhilreddy123456** [comment]
waiting for your reply.....

**Comment by nikhilreddy123456** [comment]
Hi, Waiting for your reply.....

**Comment by myflashlab** [comment]
when you receive the error ```OnConnectFailure:17 API.games APi is not available on this device.```, can you manually logout the user? since you have manually deleted the user from device, maybe it would make sense to logout the user the next time that error message happens? Let me know how it goes.

**Comment by nikhilreddy123456** [comment]
Hi, i tried in another method when onConnectFailure happen i called signout() it is getting signout correctly and in onSignoutSuccess function i called Signin() it is getting automatically signin. This method is correct or not.

**Comment by nikhilreddy123456** [comment]
Hi, Waiting for your reply.....

**Comment by nikhilreddy123456** [comment]
Hi, Waiting for your reply....

**Comment by nikhilreddy123456** [comment]
4 days back i send the message till now no response from your side.

**Comment by myflashlab** [comment]
Well, if it works, then it's fine. however, in such cases, I think it would be more appropriate not to call the signin method automatically and let user hit the button instead. Let me know if you have more questions. thanks.

**Comment by nikhilreddy123456** [comment]
Hi, In cloud Save process, I am saving total game when i clicked on ads like Reward ads app closing automatically  because at particular time save started happening so app closing.

**Comment by myflashlab** [comment]
The save process should happen when user hits the "save" button in your app. It normally shouldn't be called continuously or automatically.

**Comment by Gokul617** [comment]
Hi,

I need to implement a auto cloud save feature in my app. I'm now using the googleSignIn -ANE for it. but sometimes it appears to show a ANR dialog in certain cases. It may be due to low network i guess. I want to avoid this kind of ANR happening in my app. Also suggest me how to handle weak network while saving the app's progress in cloud server.


Please provide a solution for auto cloud save feature.

**Comment by myflashlab** [comment]
@Gokul617 will you be able to provide us with error logs? maybe you can implement [Firebase Crashlytics](https://github.com/myflashlab/Firebase-ANE/wiki/L.1-Add-Crashlytics) to your project and then provide us with the reported error logs. This way we can see what the possible problem would be and fix it. Thanks.

**Comment by nikhilreddy123456** [comment]
![ipmsgclip_r_1534937979_0](https://user-images.githubusercontent.com/39688242/44461382-3ef8cf80-a62e-11e8-9b96-785a8aac2f0b.png)

Hi, how can i get time property of saved snapshot.

**Comment by nikhilreddy123456** [comment]
Hi, Waiting for your reply.....

**Comment by nikhilreddy123456** [comment]
Hi, Waiting for your reply.....

**Comment by myflashlab** [comment]
[Here](https://github.com/myflashlab/GameServices-ANE/wiki/E.-Game-Save-Snapshots#loading-saved-games), have you checked out the ```metadata.lastModifiedTimestamp``` property?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
