### ISSUE TITLE
 ioError: GSignIn.rest.getTokens(_serverAuthCode, onTokensResult);

### ISSUE THREAD

**Issue by CrazyFlasher** [myflashlab/GoogleSignIn-ANE#13]
When I call `GSignIn.rest.getTokens(_serverAuthCode, onTokensResult);`, I get error:
```
[trace] [IOErrorEvent type="ioError" bubbles=false cancelable=false eventPhase=2 text="Error #2032: Stream Error. URL: https://www.googleapis.com/oauth2/v4/token" errorID=2032]
```

**Comment by myflashlab** [comment]
Can't duplicate this :thinking: That error shouldn't happen unless Google server is down or your mobile connection is interrupted.

**Comment by CrazyFlasher** [comment]
Just copy link `https://www.googleapis.com/oauth2/v4/token` to browser, and you will receive 404

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
