### ISSUE TITLE
Failing to access swf file's embedded resources when GSignInOptions() is used anywhere

### ISSUE THREAD

**Issue by chpla** [myflashlab/GoogleSignIn-ANE#15]
## Environment ##
* Android API Version: targetSdkVersion="23"
* iOS Version: n/a
* AIR SDK Version: 29

## Problem Description ##
Describe your problem in detail.
* Copy your manifest ```.xml``` file.
```<manifest android:installLocation="auto">
				
				<uses-sdk android:targetSdkVersion="23" android:minSdkVersion="15"/>

				<uses-permission android:name="android.permission.INTERNET"/>
				<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
				<uses-permission android:name="android.permission.GET_ACCOUNTS" />
				<uses-permission android:name="com.android.vending.BILLING" />
				<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
				<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
				<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
				<uses-permission android:name="android.permission.READ_PHONE_STATE" />
				<uses-permission android:name="android.permission.WAKE_LOCK"/>
				<application android:allowBackup="true" android:hardwareAccelerated="true" android:name="android.support.multidex.MultiDexApplication">

<activity 
								android:name="com.google.android.gms.auth.api.signin.internal.SignInHubActivity"
								android:theme="@android:style/Theme.Translucent.NoTitleBar"
								android:excludeFromRecents="true" android:exported="false"/>
								
							<service android:name="com.google.android.gms.auth.api.signin.RevocationBoundService"
								android:exported="true"
								android:permission="com.google.android.gms.auth.api.signin.permission.REVOCATION_NOTIFICATION"/>

							<activity 
								android:name="com.google.android.gms.common.api.GoogleApiActivity" 
								android:theme="@android:style/Theme.Translucent.NoTitleBar" 
								android:exported="false"/>

							<meta-data 
								android:name="com.google.android.gms.version" 
								android:value="@integer/google_play_services_version"/>

							<meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\ 68576940523"/>
</application>
			</manifest>
```
* Copy your Actionscript code.
```actionscript
var options:GSignInOptions = new GSignInOptions();
```

## Steps to Reproduce ##
Whenever I attempt to instantiate GSignInOptions() anyhwere in the code, the app will no longer be able to reference any embedded resources in the SWF at runtime (such as images and sounds embedded by using Embed metatags).

Those embedded resources are defined using Embed metatags and then referenced by variables of type Class, either by using the variable names in code directly (var myObj = new Main_foor();), or by using getDefinitionByName("Main_foo").

Both of these methods no longer work as soon as GSignInOptions() is instantiated anywhere in the code. Then this error gets thrown for each class variable:

ReferenceError: Error #1065: Variable Main_splashbarfilling is not defined.

	at runtime::ContentPlayer/loadInitialContent()
	at runtime::ContentPlayer/playRawContent()
	at runtime::ContentPlayer/playContent()
	at runtime::AppRunner/run()
	at AppEntryCommon/run()
	at global/runtime::AndroidMobileDeviceAppEntry()

Seemingly, those errors get thrown before the applciation code is even entered.

If I do not attempt to use the GSignInOptions() then this problem does not occur.

## Known Workarounds ##
None

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
