### ISSUE TITLE
Constant Value: 4 in Google signIn

### ISSUE THREAD

**Issue by BenQ12345** [myflashlab/GoogleSignIn-ANE#17]
Hi,
  If it get SlientsignIn or normal signIn it is showing **onSigninFailure:4** i checked in CommonStatus it is Showing,**The client attempted to connect to the service but the user is not signed in. The client may choose to continue without using the API or it may call startResolutionForResult(Activity, int) to prompt the user to sign in. After the sign in activity returns with RESULT_OK further attempts to connect should succeed.** 
             I have one more doubt that i am linking the app with firebase console for Analytics after that Gsignin showing  **onSigninFailure:4**. I have another app which is not linked with firebase console it is working fine. So I want to enable or disable any authentication in firebase console to get signin or not

Please provide the solution for it

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
