### ISSUE TITLE
GoogleSignIn Request more scopes than needed

### ISSUE THREAD

**Issue by noamgat** [myflashlab/GoogleSignIn-ANE#2]
I'm trying to get the minimal amount of scopes required - just "Manage This game activity on google game services" from the user. However, the consent screen still shows "View basic user information" with the G (of google+) icon next to it.

According to this doc:
https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInOptions
if DEFAULT_GAMES_SIGN_IN is used, it shouldn't ask for it. The configuration specified in the actionscript code should match it, but it doesn't seem to be working. Is there a configuration I am missing?

## Environment ##
* Android API Version: 23
* AIR SDK Version: 28

## Problem Description ##
* Copy your Actionscript code.
```actionscript
var options:GSignInOptions = new GSignInOptions();
options.requestScopes = ["https://www.googleapis.com/auth/games"];
options.requestId = false;
options.requestProfile = false;
options.requestEmail = false;
GSignIn.init(options);


```

![scopes](https://user-images.githubusercontent.com/1331304/36091115-585ab76a-0feb-11e8-8804-6b8f1603ae15.png)

**Comment by myflashlab** [comment]
currently the ANE uses ```DEFAULT_SIGN_IN``` only. will fix this now considering the latest changes to how google Auth works. **Notice:** today we launched V1.1.0 which now gives you access to refresh_token and access_token inside the app. with the older version of the ANE you had to get those tokens on server only. Now, this can optionally happen on the app side also.

**Comment by noamgat** [comment]
Thanks. This is super important for us because google put "requesting only google play services permissions" as a requirement for feature consideration nowadays.

**Comment by myflashlab** [comment]
@noamgat try this demo [googleSignIn.ane.zip](https://github.com/myflashlab/GoogleSignIn-ANE/files/1719520/googleSignIn.ane.zip) version.

## USAGE: ##
You need to set the newly added ```gamesSignIn``` property to ```true``` before initializing the ANE.
```actionscript
// depending on your app design, you must customize the Signin Options
var options:GSignInOptions = new GSignInOptions();
options.gamesSignIn = true; // set to true if you are working with Google Games Services ANE.
options.requestId = false;
options.requestProfile = false;
options.requestEmail = false;
options.requestScopes = ["https://www.googleapis.com/auth/games"];
		
// and pass the object to the initialization method of the ANE
GSignIn.init(options);
```
Let us know how it works so we can release this version with some editions being added about **access_token** and **refresh_token**.

**Comment by noamgat** [comment]
It works when I do exactly your code, but if I add requestIdToken (to authenticate with our server) it adds the plus.me scope. I think this should be avoidable

**Comment by myflashlab** [comment]
yes, it seems like google adds that internally and we don't have control over it. Anyhow, Thanks for your tests and we'll be releasing this newer version soon. I'm glad we could help. we will also update the GamesServices ANE and its documentation to be synced with the latest changes that Google has made.

**Comment by noamgat** [comment]
Got confirmation from google that this is the behavior when requesting the ID token, so it looks good. Thanks for the great support!

**Comment by myflashlab** [comment]
Thanks for your detailed explanation which helped us identify the problem and fix it. Sometimes our users are not providing any information about their problem and expect us to fix things magically! That can't happen. In your case, you explained everything and we could find the problem and of course we'd be happy to fix them :D
