### ISSUE TITLE
$account.gender ?

### ISSUE THREAD

**Issue by AlexUrrutia** [myflashlab/GoogleSignIn-ANE#4]
Hello, is it possible to get the user's gender?

It is very important for our app to get the user's gender from Google if public.

I don't seem to get it, I get Name and photoURL at the moment
```
$account.displayName;
$account.photoUrl;
```
_$account.gender_

what can I do?
Thanks

**Comment by myflashlab** [comment]
hmm, This is probably doable with https://developers.google.com/people/ It's a REST API so, it should be the solution. The Google SignIn ANE does not provide such information. but when using it, you can access different APIs. We'd be happy to hear how things go.

**Comment by AlexUrrutia** [comment]
@myflashlab yeah I already solved it, I used the access token and called `https://www.googleapis.com/plus/v1/people/me?` to get the user's plus profile info including gender, thanks
