### ISSUE TITLE
GoogleSignIn-ANE in MyFlashLabClub_ANEs_package.zip

### ISSUE THREAD

**Issue by misterPitty** [myflashlab/GoogleSignIn-ANE#5]
Hi. When will you add new versions of GameServices-ANE and GoogleSignIn-ANE in MyFlashLabClub_ANEs_package.zip for MyFlashLabs Club Membership buyers. I use this ANEs in my project and i need "not a demo versions" for release.

**Comment by myflashlab** [comment]
will update it a.s.a.p... latest are available through ANELA... the packagr should be updated very soon anyhow....

**Comment by myflashlab** [comment]
Please grab the latest package ( # 62) from your control panel. More updates are coming soon but we updated the package just for you guys to have access to the latest ANEs. cheers.
