### ISSUE TITLE
Got error Constant Value: 10

### ISSUE THREAD

**Issue by greatpatawee** [myflashlab/GoogleSignIn-ANE#7]
Hi i'm got error when use GSignIn.signin();

onSigninFailure: 10;

i'm looking in https://developers.google.com/android/reference/com/google/android/gms/common/api/CommonStatusCodes

number 10 is mean 

public static final int DEVELOPER_ERROR
The application is misconfigured. This error is not recoverable and will be treated as fatal. The developer should look at the logs after this to determine more actionable information.

but i'm already configured clientserverID in options.requestIdToken and options.requestServerAuthCode

how to solve it

Thk alot

**Comment by greatpatawee** [comment]
My manifest file

<?xml version="1.0" encoding="utf-8" standalone="no" ?>

<application xmlns="http://ns.adobe.com/air/application/30.0">
  <id>com.blueelp.halal</id>
  <versionNumber>1.0.2</versionNumber>
  <versionLabel></versionLabel>
  <filename>Main</filename>
  <description/>
  <name>Main</name>
  <copyright/>
  <initialWindow>
    <content>Main.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    <aspectRatio>portrait</aspectRatio>
    <renderMode>gpu</renderMode>
    <autoOrients>false</autoOrients></initialWindow>
  <icon>
    
    
    
    
    
  </icon>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  <android>
        <manifestAdditions><![CDATA[<manifest android:installLocation="auto">
	
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
	<uses-sdk android:targetSdkVersion="23"/>
	
	<application android:name="android.support.multidex.MultiDexApplication">
		
		<activity 
			android:name="com.google.android.gms.auth.api.signin.internal.SignInHubActivity"
			android:theme="@android:style/Theme.Translucent.NoTitleBar"
			android:excludeFromRecents="true" android:exported="false"/>
			
		<service android:name="com.google.android.gms.auth.api.signin.RevocationBoundService"
			android:exported="true"
			android:permission="com.google.android.gms.auth.api.signin.permission.REVOCATION_NOTIFICATION"/>

		<activity 
			android:name="com.google.android.gms.common.api.GoogleApiActivity" 
			android:theme="@android:style/Theme.Translucent.NoTitleBar" 
			android:exported="false"/>

		<meta-data 
			android:name="com.google.android.gms.version" 
			android:value="@integer/google_play_services_version"/>
		
	</application>
</manifest>
]]></manifestAdditions>
	</android>
  

  
  <extensions>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.auth</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.auth.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
    <extensionID>com.myflashlab.air.extensions.google.signin</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
  </extensions>
</application>

**Comment by greatpatawee** [comment]
My manifest file

`<?xml version="1.0" encoding="utf-8" standalone="no" ?>

<application xmlns="http://ns.adobe.com/air/application/30.0">
  <id>com.blueelp.halal</id>
  <versionNumber>1.0.2</versionNumber>
  <versionLabel></versionLabel>
  <filename>Main</filename>
  <description/>
  <name>Main</name>
  <copyright/>
  <initialWindow>
    <content>Main.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    <aspectRatio>portrait</aspectRatio>
    <renderMode>gpu</renderMode>
    <autoOrients>false</autoOrients></initialWindow>
  <icon>
    
    
    
    
    
  </icon>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  <android>
        <manifestAdditions><![CDATA[<manifest android:installLocation="auto">
	
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
	<uses-sdk android:targetSdkVersion="23"/>
	
	<application android:name="android.support.multidex.MultiDexApplication">
		
		<activity 
			android:name="com.google.android.gms.auth.api.signin.internal.SignInHubActivity"
			android:theme="@android:style/Theme.Translucent.NoTitleBar"
			android:excludeFromRecents="true" android:exported="false"/>
			
		<service android:name="com.google.android.gms.auth.api.signin.RevocationBoundService"
			android:exported="true"
			android:permission="com.google.android.gms.auth.api.signin.permission.REVOCATION_NOTIFICATION"/>

		<activity 
			android:name="com.google.android.gms.common.api.GoogleApiActivity" 
			android:theme="@android:style/Theme.Translucent.NoTitleBar" 
			android:exported="false"/>

		<meta-data 
			android:name="com.google.android.gms.version" 
			android:value="@integer/google_play_services_version"/>
		
	</application>
</manifest>
]]></manifestAdditions>
	</android>
  

  
  <extensions>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.auth</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.auth.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
    <extensionID>com.myflashlab.air.extensions.google.signin</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
  </extensions>
</application>
`

**Comment by greatpatawee** [comment]
I'm use logcat in debug mode only see number 10 in error how to open AndroidStudio logcat window

**Comment by mtilhan** [comment]
I have the same problem. When i searched the error code 10 its meand developer error but thats not mean anything. My SHA1 fingerprint is valid and same as application. 

When we using this ANE are we must activate App signing on Google Play Developer Console ?

Is this Google Login is related about Firebase? Am i do enable Google login on Firebase console?

**Comment by mtilhan** [comment]
I had same problem and its coused by wrong SHA1 fingerprint key. Make sure you use correct key.

**Comment by hagiangnam** [comment]
i had the same and , please check and response as soon as possible :((

**Comment by myflashlab** [comment]
When GoogleSignin returns error code ```10```, that means that there's a developer mistake. it could be a wrong SHA1 as @mtilhan suggested and it could even be a wrong app package name. Notice that AIR SDK ads ```air.``` prefix by default to the beginning of your package name.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
