### ISSUE TITLE
Not able to Compile Sample Project

### ISSUE THREAD

**Issue by garymich** [myflashlab/GoogleSignIn-ANE#8]
## Environment ##
* Android API Version: 26
* iOS Version: N/A
* AIR SDK Version: 30

## Problem Description ##
When trying to compile the sample project we can the following compile error: C:\Users\Gary\Documents\Adobe\Animate Projects\GoogleSignInTest\src\Main.as, Line 311, Column 8	1120: Access of undefined property _idToken.
I have looked in the source file provided and though your function named: gettokeninfo  referecnes _idToken it is not defined anywhere in the source file. What are we missing ?

* Copy your manifest ```.xml``` file.
```xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<application xmlns="http://ns.adobe.com/air/application/26.0">
  <id>com.GoogleSignInTest</id>
  <versionNumber>1.0.0</versionNumber>
  <versionLabel/>
  <filename>GoogleSignInTest</filename>
  <description/>
  <name>GoogleSignInTest</name>
  <copyright/>
  <initialWindow>
    <content>GoogleSignInTest.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>false</fullScreen>
    <aspectRatio>portrait</aspectRatio>
    <renderMode>cpu</renderMode>
    <autoOrients>false</autoOrients>
  </initialWindow>
  <icon/>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  
  <android>
    <manifestAdditions><![CDATA[<manifest android:installLocation="auto" >
  <application>
    <activity android:name="com.google.android.gms.auth.api.signin.internal.SignInHubActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:excludeFromRecents="true" android:exported="false"/>
    <service android:name="com.google.android.gms.auth.api.signin.RevocationBoundService" android:exported="true" android:permission="com.google.android.gms.auth.api.signin.permission.REVOCATION_NOTIFICATION"/>
    <activity android:name="com.google.android.gms.common.api.GoogleApiActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:exported="false"/>
    <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>
    <meta-data android:name="com.myflashlabs.aneLab.id" android:value="[xxxxx]"/>
  </application>
  <uses-sdk android:minSdkVersion="15" android:targetSdkVersion="26"/>
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
</manifest>]]></manifestAdditions>
  </android>
</application>
```
* Copy your Actionscript code.

```actionscript
package
{
import com.doitflash.consts.Direction;
import com.doitflash.consts.Orientation;
import com.doitflash.mobileProject.commonCpuSrc.DeviceInfo;
import com.doitflash.starling.utils.list.List;
import com.doitflash.text.modules.MySprite;

import com.luaye.console.C;

import flash.desktop.NativeApplication;
import flash.desktop.SystemIdleMode;
import flash.display.Sprite;
import flash.display.StageAlign;
import flash.display.StageScaleMode;
import flash.events.Event;
import flash.events.InvokeEvent;
import flash.events.KeyboardEvent;
import flash.events.MouseEvent;
import flash.text.AntiAliasType;
import flash.text.TextField;
import flash.text.TextFieldAutoSize;
import flash.text.TextFormat;
import flash.text.TextFormatAlign;
import flash.ui.Keyboard;
import flash.ui.Multitouch;
import flash.ui.MultitouchInputMode;

import com.myflashlab.air.extensions.dependency.OverrideAir;
import com.myflashlab.air.extensions.gSignIn.*;


/**
 * ...
 * @author Hadi Tavakoli - 1/30/2018 11:25 AM
 */
public class Main extends Sprite
{
	private const BTN_WIDTH:Number = 150;
	private const BTN_HEIGHT:Number = 60;
	private const BTN_SPACE:Number = 2;
	private var _txt:TextField;
	private var _body:Sprite;
	private var _list:List;
	private var _numRows:int = 1;
	
	private var _serverAuthCode:String;
	
	public function Main():void
	{
		Multitouch.inputMode = MultitouchInputMode.GESTURE;
		NativeApplication.nativeApplication.addEventListener(Event.ACTIVATE, handleActivate);
		NativeApplication.nativeApplication.addEventListener(Event.DEACTIVATE, handleDeactivate);
		NativeApplication.nativeApplication.addEventListener(InvokeEvent.INVOKE, onInvoke);
		NativeApplication.nativeApplication.addEventListener(KeyboardEvent.KEY_DOWN, handleKeys);
		
		stage.addEventListener(Event.RESIZE, onResize);
		stage.scaleMode = StageScaleMode.NO_SCALE;
		stage.align = StageAlign.TOP_LEFT;
		
		C.startOnStage(this, "`");
		C.commandLine = false;
		C.commandLineAllowed = false;
		C.x = 20;
		C.width = 250;
		C.height = 150;
		C.strongRef = true;
		C.visible = true;
		C.scaleX = C.scaleY = DeviceInfo.dpiScaleMultiplier;
		
		_txt = new TextField();
		_txt.autoSize = TextFieldAutoSize.LEFT;
		_txt.antiAliasType = AntiAliasType.ADVANCED;
		_txt.multiline = true;
		_txt.wordWrap = true;
		_txt.embedFonts = false;
		_txt.htmlText = "<font face='Arimo' color='#333333' size='20'><b>GoogleSignIn ANE for Adobe Air V" + GSignIn.VERSION + "</font>";
		_txt.scaleX = _txt.scaleY = DeviceInfo.dpiScaleMultiplier;
		this.addChild(_txt);
		
		_body = new Sprite();
		this.addChild(_body);
		
		_list = new List();
		_list.holder = _body;
		_list.itemsHolder = new Sprite();
		_list.orientation = Orientation.VERTICAL;
		_list.hDirection = Direction.LEFT_TO_RIGHT;
		_list.vDirection = Direction.TOP_TO_BOTTOM;
		_list.space = BTN_SPACE;
		
		init();
		onResize();
	}
	
	private function onInvoke(e:InvokeEvent):void
	{
		NativeApplication.nativeApplication.removeEventListener(InvokeEvent.INVOKE, onInvoke);
	}
	
	private function handleActivate(e:Event):void
	{
		NativeApplication.nativeApplication.systemIdleMode = SystemIdleMode.KEEP_AWAKE;
	}
	
	private function handleDeactivate(e:Event):void
	{
		NativeApplication.nativeApplication.systemIdleMode = SystemIdleMode.NORMAL;
	}
	
	private function handleKeys(e:KeyboardEvent):void
	{
		if(e.keyCode == Keyboard.BACK)
		{
			e.preventDefault();
			NativeApplication.nativeApplication.exit();
		}
	}
	
	private function onResize(e:* = null):void
	{
		if(_txt)
		{
			_txt.width = stage.stageWidth * (1 / DeviceInfo.dpiScaleMultiplier);
			
			C.x = 0;
			C.y = _txt.y + _txt.height + 0;
			C.width = stage.stageWidth * (1 / DeviceInfo.dpiScaleMultiplier);
			C.height = 300 * (1 / DeviceInfo.dpiScaleMultiplier);
		}
		
		if(_list)
		{
			_numRows = Math.floor(stage.stageWidth / (BTN_WIDTH * DeviceInfo.dpiScaleMultiplier + BTN_SPACE));
			_list.row = _numRows;
			_list.itemArrange();
		}
		
		if(_body)
		{
			_body.y = stage.stageHeight - _body.height;
		}
	}
	
	private function myDebuggerDelegate($ane:String, $class:String, $msg:String):void
	{
		trace("["+$ane+"-"+$class+"]"+$msg);
	}
	
	private function init():void
	{
		// remove this line when building for production
		OverrideAir.enableDebugger(myDebuggerDelegate);
		
		// depending on your app design, you must customize the Signin Options
		var options:GSignInOptions = new GSignInOptions();
		options.gamesSignIn = false; // (Android only) set to true if you are working with Google Games Services ANE.
		options.requestIdToken = "serverClientId"; // get the client ID of your server
		options.requestServerAuthCode = "serverClientId"; // get the client ID of your server
		options.requestEmail = true;
		options.requestProfile = true;
		options.requestId = true;
		// get the iOS clientID from the .plist file you downloaded when you were setting up the GSignin
		options.clientIdForiOS = "clientIdForiOS";
		
		// and pass the object to the initialization method of the ANE
		GSignIn.init(options);
		
		// If you want to access refresh_token and access_token on the client side, pass your web clientID and secret.
		GSignIn.rest.webClientId = "webClientId";
		GSignIn.rest.webClientSecret = "webClientSecret";
		
		// Then, add listeners
		GSignIn.listener.addEventListener(GSignInEvents.SILENT_SIGNIN_SUCCESS, onSilentSigninSuccess);
		GSignIn.listener.addEventListener(GSignInEvents.SILENT_SIGNIN_FAILURE, onSilentSigninFailure);
		GSignIn.listener.addEventListener(GSignInEvents.SIGNIN_SUCCESS, onSigninSuccess);
		GSignIn.listener.addEventListener(GSignInEvents.SIGNIN_FAILURE, onSigninFailure);
		GSignIn.listener.addEventListener(GSignInEvents.SIGNOUT_SUCCESS, onSignoutSuccess);
		GSignIn.listener.addEventListener(GSignInEvents.SIGNOUT_FAILURE, onSignoutFailure);
		GSignIn.listener.addEventListener(GSignInEvents.REVOKE_ACCESS_SUCCESS, onRevokeAccessSuccess);
		GSignIn.listener.addEventListener(GSignInEvents.REVOKE_ACCESS_FAILURE, onRevokeAccessFailure);
		GSignIn.listener.addEventListener(GSignInEvents.REQUEST_PERMISSION_SUCCESS, onRequestSuccess);
		GSignIn.listener.addEventListener(GSignInEvents.REQUEST_PERMISSION_FAILURE, onRequestFailure);
		
		// on iOS you may optionally add the following listener to know the state of the login window
		GSignIn.listener.addEventListener(GSignInEvents.LOGIN_WINDOW_STATUS, onSigninWindowStateChanged);
		
		// check if user is already loggedin or not
		var account:GAccount = GSignIn.signedInAccount;
		if(account)
		{
			showUserInfo(account);
		}
		else
		{
			// You should first check if user can signin silently, if she can't, use the signin() method
			GSignIn.silentSignIn();
		}
		
		
		//----------------------------------------------------------------------
		
		var btn0:MySprite = createBtn("signin");
		btn0.addEventListener(MouseEvent.CLICK, signin);
		_list.add(btn0);
		
		function signin(e:MouseEvent):void
		{
			if(!GSignIn.signedInAccount) GSignIn.signin();
			else C.log("You are already signed in!");
		}
		
		//----------------------------------------------------------------------
		
		var btn1:MySprite = createBtn("signout");
		btn1.addEventListener(MouseEvent.CLICK, signout);
		_list.add(btn1);
		
		function signout(e:MouseEvent):void
		{
			if(GSignIn.signedInAccount) GSignIn.signOut();
			else C.log("You are NOT signed in!");
		}
		
		//----------------------------------------------------------------------
		
		var btn2:MySprite = createBtn("revoke access");
		btn2.addEventListener(MouseEvent.CLICK, revokeAccess);
		_list.add(btn2);
		
		function revokeAccess(e:MouseEvent):void
		{
			if(GSignIn.signedInAccount) GSignIn.revokeAccess();
			else C.log("You are NOT signed in!");
		}
		
		//----------------------------------------------------------------------
		
		var btn4:MySprite = createBtn("account info");
		btn4.addEventListener(MouseEvent.CLICK, getAccountInfo);
		_list.add(btn4);
		
		function getAccountInfo(e:MouseEvent):void
		{
			var account:GAccount = GSignIn.signedInAccount;
			
			if(!account) C.log("You are not logged in!");
			else showUserInfo(account);
		}
		
		//----------------------------------------------------------------------
		
		var btn3:MySprite = createBtn("ask extra permission");
		btn3.addEventListener(MouseEvent.CLICK, askPermission);
		_list.add(btn3);
		
		function askPermission(e:MouseEvent):void
		{
			if(!GSignIn.hasPermissions([GScopes.DRIVE_APPFOLDER]))
			{
				GSignIn.requestPermissions([GScopes.DRIVE_APPFOLDER]);
			}
			else
			{
				C.log("This permission is already granted!");
			}
		}
		
		//----------------------------------------------------------------------
		
		var btn5:MySprite = createBtn("getTokens");
		btn5.addEventListener(MouseEvent.CLICK, getTokens);
		_list.add(btn5);
		
		function getTokens(e:MouseEvent):void
		{
			if(!_serverAuthCode)
			{
				C.log("serverAuthCode must be available for this method to work");
				return;
			}
			
			GSignIn.rest.getTokens(_serverAuthCode, onTokensResult);
		}
		
		function onTokensResult($restTokens:GRestTokens, $error:Error):void
		{
			if($error)
			{
				trace($error.message);
				return;
			}
			
			trace("------------------------------");
			trace("access_token: " + 	$restTokens.access_token);
			trace("token_type: " + 		$restTokens.token_type);
			trace("expires_in: " + 		$restTokens.expires_in);
			trace("refresh_token: " + 	$restTokens.refresh_token);
			trace("id_token: " + 		$restTokens.id_token);
			trace("------------------------------");
		}
		
		//----------------------------------------------------------------------
		
		var btn6:MySprite = createBtn("tokenInfo");
		btn6.addEventListener(MouseEvent.CLICK, tokenInfo);
		_list.add(btn6);
		
		function tokenInfo(e:MouseEvent):void
		{
			if(!_idToken)
			{
				C.log("idToken must be available for this method to work");
				return;
			}
			
			GSignIn.rest.tokenInfo(_idToken, onTokensInfoResult);
		}
		
		function onTokensInfoResult($info:Object, $error:Error):void
		{
			if($error)
			{
				trace($error.message);
				return;
			}
			
			// read more about tokeninfo here:
			// https://developers.google.com/identity/sign-in/web/backend-auth#calling-the-tokeninfo-endpoint
			trace("------------------------------");
			trace(JSON.stringify($info));
			trace("------------------------------");
		}
		
		//----------------------------------------------------------------------
	}
	
	private function onRequestSuccess(e:GSignInEvents):void
	{
		C.log("----------------");
		C.log("onRequestSuccess");
		showUserInfo(e.account);
	}
	
	private function onRequestFailure(e:GSignInEvents):void
	{
		C.log("onRequestFailure: " + e.msg);
	}
	
	private function onRevokeAccessSuccess(e:GSignInEvents):void
	{
		C.log("onRevokeAccessSuccess");
	}
	
	private function onRevokeAccessFailure(e:GSignInEvents):void
	{
		C.log("onRevokeAccessFailure: " + e.msg);
	}
	
	private function onSignoutSuccess(e:GSignInEvents):void
	{
		C.log("onSignoutSuccess");
	}
	
	private function onSignoutFailure(e:GSignInEvents):void
	{
		C.log("onSignoutFailure: " + e.msg);
	}
	
	private function onSigninSuccess(e:GSignInEvents):void
	{
		C.log("----------------");
		C.log("onSigninSuccess");
		showUserInfo(e.account);
	}
	
	private function onSigninFailure(e:GSignInEvents):void
	{
		C.log("onSigninFailure: " + e.msg);
	}
	
	private function onSilentSigninSuccess(e:GSignInEvents):void
	{
		C.log("----------------");
		C.log("onSilentSigninSuccess");
		showUserInfo(e.account);
	}
	
	private function onSilentSigninFailure(e:GSignInEvents):void
	{
		/*
			check the meaning of failure code here:
			https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInStatusCodes
			https://developers.google.com/android/reference/com/google/android/gms/common/api/CommonStatusCodes
		 */
		C.log("onSilentSigninFailure: " + e.msg);
	}
	
	private function onSigninWindowStateChanged(e:GSignInEvents):void
	{
		switch(e.state)
		{
			case GSignInEvents.SIGNIN_WINDOW_ERROR:
				trace("onSigninWindowStateChanged error: " + e.msg);
				break;
			case GSignInEvents.SIGNIN_WINDOW_DISPATCH:
				trace("SIGNIN_WINDOW_DISPATCH");
				break;
		}
	}
	
	private function showUserInfo($account:GAccount):void
	{
		_serverAuthCode = $account.serverAuthCode;
		
		C.log("displayName: " + 	$account.displayName);
		C.log("email: " + 			$account.email);
		C.log("familyName: " + 		$account.familyName);
		C.log("givenName: " + 		$account.givenName);
		C.log("id: " + 				$account.id);
		C.log("idToken: " + 		$account.idToken);
		C.log("photoUrl: " + 		$account.photoUrl);
		for(var i:int=0; i < $account.scopes.length; i++)
		{
			C.log("\t" + $account.scopes[i]);
		}
		C.log("serverAuthCode: " + 	$account.serverAuthCode);
	}
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	private function createBtn($str:String):MySprite
	{
		var sp:MySprite = new MySprite();
		sp.addEventListener(MouseEvent.MOUSE_OVER, onOver);
		sp.addEventListener(MouseEvent.MOUSE_OUT, onOut);
		sp.addEventListener(MouseEvent.CLICK, onOut);
		sp.bgAlpha = 1;
		sp.bgColor = 0xDFE4FF;
		sp.drawBg();
		sp.width = BTN_WIDTH * DeviceInfo.dpiScaleMultiplier;
		sp.height = BTN_HEIGHT * DeviceInfo.dpiScaleMultiplier;
		
		function onOver(e:MouseEvent):void
		{
			sp.bgAlpha = 1;
			sp.bgColor = 0xFFDB48;
			sp.drawBg();
		}
		
		function onOut(e:MouseEvent):void
		{
			sp.bgAlpha = 1;
			sp.bgColor = 0xDFE4FF;
			sp.drawBg();
		}
		
		var format:TextFormat = new TextFormat("Arimo", 16, 0x666666, null, null, null, null, null, TextFormatAlign.CENTER);
		
		var txt:TextField = new TextField();
		txt.autoSize = TextFieldAutoSize.LEFT;
		txt.antiAliasType = AntiAliasType.ADVANCED;
		txt.mouseEnabled = false;
		txt.multiline = true;
		txt.wordWrap = true;
		txt.scaleX = txt.scaleY = DeviceInfo.dpiScaleMultiplier;
		txt.width = sp.width * (1 / DeviceInfo.dpiScaleMultiplier);
		txt.defaultTextFormat = format;
		txt.text = $str;
		
		txt.y = sp.height - txt.height >> 1;
		sp.addChild(txt);
		
		return sp;
	}
}
	
}
```

## Steps to Reproduce ##
The error occurs when I try to debug the application.

**Comment by garymich** [comment]
Okay, I do not know if I did this correctly but I defined a variable of that name of type string and it then compiled fine. 

I then went to debug it on my android phone and got a different appt tool error message regarding the android:keyboardNavigationCluster. 

I changed the target for my project to: AIR 30.0.0.107 for Android and tried to publish again. This time it did publish it but displayed a message box saying the APK was packaged successfully, but a warning occurred. NOTE: the application has been packaged with a captive runtime. On my phone after I close the message box it shows GoogleSignInTest has stopped. - Close app. My project also exits debug mode.

The contents of my output window is as follows:
Waiting for Player to connect...
[SWF] GoogleSignInTest.swf - 143195 bytes after decompression
[gSignin-AirCommand]init begin
[gSignin-AirCommand]convertJsonToGoogleSignInOptions begin
[gSignin-AirCommand]$str:{"requestId":true,"gamesSignIn":false,"requestEmail":true,"setHostedDomain":"","requestScopes":[],"setAccountName":"","requestProfile":true,"forceCodeForRefreshToken":false,"requestIdToken":"serverClientId","requestServerAuthCode":"serverClientId"}
[gSignin-AirCommand]convertJsonToGoogleSignInOptions 1.0
[gSignin-AirCommand]convertJsonToGoogleSignInOptions 2.0
[gSignin-AirCommand]convertJsonToGoogleSignInOptions 3.0
[gSignin-AirCommand]convertJsonToGoogleSignInOptions 4.0
[gSignin-AirCommand]convertJsonToGoogleSignInOptions 5.0
[gSignin-AirCommand]convertJsonToGoogleSignInOptions end
[gSignin-AirCommand]init end
[gSignin-AirCommand]getLastSignedInAccount begin
[gSignin-AirCommand]getLastSignedInAccount end
[gSignin-AirCommand]getLastSignedInAccount begin
[gSignin-AirCommand]getLastSignedInAccount end
Debug session terminated.

**Comment by garymich** [comment]
Not sure why wither. However, I checked it and it is now set to 30 but still acts the same.

**Comment by myflashlab** [comment]
Will you please post your current latest manifest .xml file here?

**Comment by garymich** [comment]
As per your request see below:

<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<application xmlns="http://ns.adobe.com/air/application/30.0">
  <id>com.GoogleSignInTest</id>
  <versionNumber>1.0.0</versionNumber>
  <versionLabel/>
  <filename>GoogleSignInTest</filename>
  <description/>
  <name>GoogleSignInTest</name>
  <copyright/>
  <initialWindow>
    <content>GoogleSignInTest.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>false</fullScreen>
    <aspectRatio>portrait</aspectRatio>
    <renderMode>cpu</renderMode>
    <autoOrients>false</autoOrients>
  </initialWindow>
  <icon/>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  
  <android>
    <manifestAdditions><![CDATA[<manifest>
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
</manifest>]]></manifestAdditions>
  </android>
  <supportedLanguages>en fr</supportedLanguages>
  
  <extensions>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.auth.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.auth</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.google.signin</extensionID>
  </extensions>
</application>

**Comment by garymich** [comment]
Looks like I mate a mistake previously, see below:

<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<application xmlns="http://ns.adobe.com/air/application/30.0">
  <id>com.GoogleSignInTest</id>
  <versionNumber>1.0.0</versionNumber>
  <versionLabel/>
  <filename>GoogleSignInTest</filename>
  <description/>
  <name>GoogleSignInTest</name>
  <copyright/>
  <initialWindow>
    <content>GoogleSignInTest.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>false</fullScreen>
    <aspectRatio>portrait</aspectRatio>
    <renderMode>cpu</renderMode>
    <autoOrients>false</autoOrients>
  </initialWindow>
  <icon/>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  
  <android>
    <manifestAdditions><![CDATA[<manifest>
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
</manifest>]]></manifestAdditions>
  </android>
  <supportedLanguages>en fr</supportedLanguages>
  <extensions>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.auth.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.auth</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.google.signin</extensionID>
  </extensions>
</application>

**Comment by garymich** [comment]
See below please:

``<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<application xmlns="http://ns.adobe.com/air/application/30.0">
  <id>com.GoogleSignInTest</id>
  <versionNumber>1.0.0</versionNumber>
  <versionLabel/>
  <filename>GoogleSignInTest</filename>
  <description/>
  <name>GoogleSignInTest</name>
  <copyright/>
  <initialWindow>
    <content>GoogleSignInTest.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>false</fullScreen>
    <aspectRatio>portrait</aspectRatio>
    <renderMode>cpu</renderMode>
    <autoOrients>false</autoOrients>
  </initialWindow>
  <icon/>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  
  <android>
    <manifestAdditions><![CDATA[<manifest>
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
</manifest>]]></manifestAdditions>
  </android>
  <supportedLanguages>en fr</supportedLanguages>
  <extensions>
    <extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.auth.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.auth</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.base</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.tasks</extensionID>
    <extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
    <extensionID>com.myflashlab.air.extensions.google.signin</extensionID>
  </extensions>
</application>

**Comment by myflashlab** [comment]
Thanks, but I'm confused now. Because your manifest is missing a lot of information. just compare the android tag content with the sample codes https://github.com/myflashlab/GoogleSignIn-ANE#air-xml-manifest

if you are using the ANELAB, these settings will be added automatically. I'm not sure why you are missing them. I would say, open up your ```.mal``` file again and remove all ANEs and then add them back. Make sure your manifest .xml file is not edited somewhere else.

As a side note, please read the [markdown](https://guides.github.com/features/mastering-markdown/) format to learn more about how comments in GitHub work. I've been editing your posts since the first one so the codes would show correctly :)

**Comment by garymich** [comment]
My apologies after a few attempts I located the button that would allow me to insert cod. My last comment is the complete manifest nd I believe it is correct.

Sent from Mail for Windows 10
